name: 'Check linked issues'

description: 'Check if pull requests have their corresponding issues.'

branding:
  icon: "check-square"
  color: "green"

inputs:
  github-token:
    description: "Your Github token, it's already available to your Github action."
    required: false
    default: ${{ github.token }}
  exclude-branches:
    description: "A comma-separated list of patterns to ignore source branches. (Any pattern supported by `minimatch`)"
    required: false
    default: ""
  exclude-labels:
    description: "A comma-separated list of labels to ignore."
    required: false
    default: ""
  comment:
    description: "A boolean value that allow the action to create a comment"
    required: false
    default: "true"
  custom-body-comment:
    description: "Custom body PR comment"
    required: false
    default: "No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)"

outputs:
  linked_issues_count:
    description: 'The total number of issues linked to your pull request.'
  issues:
    description: 'A stringified array containing the numbers of the linked issues, of the form ["some/repo#123", "another/repository#456"]'

runs:
  using: 'node16'
  main: 'dist/index.js'
